export const GET_ADVANCE = "GET_ADVANCE";
export const DELETE_ADVANCE = "DELETE_ADVANCE";
export const DETAIL_ADVANCE = "DETAIL_ADVANCE";
export const ADD_ADVANCE = "ADD_ADVANCE";
export const UPDATE_ADVANCE = "UPDATE_ADVANCE";

export const GET_INCOME = "GET_INCOME";
export const DETAIL_INCOME = "DETAIL_INCOME";
export const DELETE_INCOME = "DELETE_INCOME";
export const ADD_INCOME = "ADD_INCOME";
export const UPDATE_INCOME = "UPDATE_INCOME";

export const GET_EXPENDITURE = "GET_EXPENDITURE";
export const DETAIL_EXPENDITURE = "DETAIL_EXPENDITURE";
export const DELETE_EXPENDITURE = "DELETE_EXPENDITURE";
export const ADD_EXPENDITURE = "ADD_EXPENDITURE";
export const UPDATE_EXPENDITURE = "UPDATE_EXPENDITURE";

export const GET_PAYROLL = "GET_PAYROLL";
export const DETAIL_PAYROLL = "DETAIL_PAYROLL";
export const DELETE_PAYROLL = "DELETE_PAYROLL";
export const ADD_PAYROLL = "ADD_PAYROLL";
export const UPDATE_PAYROLL = "UPDATE_PAYROLL";

export const GET_REQUISITION = "GET_REQUISITION";
export const DETAIL_REQUISITION = "DETAIL_REQUISITION";
export const DELETE_REQUISITION = "DELETE_REQUISITION";
export const ADD_REQUISITION = "ADD_REQUISITION";
export const UPDATE_REQUISITION = "UPDATE_REQUISITION";

export const GET_TOOL = "GET_TOOL";
export const DETAIL_TOOL = "DETAIL_TOOL";
export const DELETE_TOOL = "DELETE_TOOL";
export const ADD_TOOL = "ADD_TOOL";
export const UPDATE_TOOL = "UPDATE_TOOL";

export const GET_TOOLBINCARD = "GET_TOOLBINCARD";
export const DETAIL_TOOLBINCARD = "DETAIL_TOOLBINCARD";
export const DELETE_TOOLBINCARD = "DELETE_TOOLBINCARD";
export const ADD_TOOLBINCARD = "ADD_TOOLBINCARD";
export const UPDATE_TOOLBINCARD = "UPDATE_TOOLBINCARD";

export const GET_CONSUMABLE = "GET_CONSUMABLE";
export const DETAIL_CONSUMABLE = "DETAIL_CONSUMABLE";
export const DELETE_CONSUMABLE = "DELETE_CONSUMABLE";
export const ADD_CONSUMABLE = "ADD_CONSUMABLE";
export const UPDATE_CONSUMABLE = "UPDATE_CONSUMABLE";

export const GET_NEWCONSUMABLE = "GET_NEWCONSUMABLE";
export const DETAIL_NEWCONSUMABLE = "DETAIL_NEWCONSUMABLE";
export const DELETE_NEWCONSUMABLE = "DELETE_NEWCONSUMABLE";
export const ADD_NEWCONSUMABLE = "ADD_NEWCONSUMABLE";
export const UPDATE_NEWCONSUMABLE = "UPDATE_NEWCONSUMABLE";

export const GET_HARVEST = "GET_HARVEST";
export const DETAIL_HARVEST = "DETAIL_HARVEST";
export const DELETE_HARVEST = "DELETE_HARVEST";
export const ADD_HARVEST = "ADD_HARVEST";
export const UPDATE_HARVEST = "UPDATE_HARVEST";

export const GET_USER = "GET_USER";
export const DETAIL_USER = "DETAIL_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";

export const GET_PERSONNEL = "GET_PERSONNEL";
export const DETAIL_PERSONNEL = "DETAIL_PERSONNEL";
export const DELETE_PERSONNEL = "DELETE_PERSONNEL";
export const ADD_PERSONNEL = "ADD_PERSONNEL";
export const UPDATE_PERSONNEL = "UPDATE_PERSONNEL";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const DETAIL_CUSTOMER = "DETAIL_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const GET_SUPPLIER = "GET_SUPPLIER";
export const DETAIL_SUPPLIER = "DETAIL_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";

