export const GET_ADVANCE = "GET_ADVANCE";
export const DELETE_ADVANCE = "DELETE_ADVANCE";
export const DETAIL_ADVANCE = "DETAIL_ADVANCE";

export const ADD_ADVANCE = "ADD_ADVANCE";
export const UPDATE_ADVANCE = "UPDATE_ADVANCE";

export const GET_INCOME = "GET_INCOME";
export const DETAIL_INCOME = "DETAIL_INCOME";
export const DELETE_INCOME = "DELETE_INCOME";
export const ADD_INCOME = "ADD_INCOME";
export const UPDATE_INCOME = "UPDATE_INCOME";

export const GET_EXPENDITURE = "GET_EXPENDITURE";
export const DETAIL_EXPENDITURE = "DETAIL_EXPENDITURE";
export const DELETE_EXPENDITURE = "DELETE_EXPENDITURE";
export const ADD_EXPENDITURE = "ADD_EXPENDITURE";
export const UPDATE_EXPENDITURE = "UPDATE_EXPENDITURE";

export const GET_PAYROLL = "GET_PAYROLL";
export const DETAIL_PAYROLL = "DETAIL_PAYROLL";
export const DELETE_PAYROLL = "DELETE_PAYROLL";
export const ADD_PAYROLL = "ADD_PAYROLL";
export const UPDATE_PAYROLL = "UPDATE_PAYROLL";

export const GET_REQUISITION = "GET_REQUISITION";
export const DETAIL_REQUISITION = "DETAIL_REQUISITION";
export const DELETE_REQUISITION = "DELETE_REQUISITION";
export const ADD_REQUISITION = "ADD_REQUISITION";
export const UPDATE_REQUISITION = "UPDATE_REQUISITION";

// export const GET_USERS = "GET_USERS";
// export const ADD_USER = "ADD_USER";
// export const DELETE_USER = "DELETE_USER";
// export const UPDATE_USER = "UPDATE_USER";
